  library(matrixStats)
  library(dplyr)
  library(reshape2)
  library(cmapR)
  library(psych)
####################################################################################################
#Step 1: Calculate the similarity matrix by Spearman correlation analysis
  DR_cal_corr<-function(path_input,path_output,cell_list){
    setwd(path_input)
    path_sh_gctx=paste0(path_input,"sh/")
    path_cp_gctx=paste0(path_input,"cp/")
    
    for (i in 1:length(cell_list)){
      print(i)
      setwd(path_sh_gctx)
      exp_sh<-parse_gctx(paste0(cell_list[i],"_sh_test.gctx"))
      exp_sh<-exp_sh@mat
      
      setwd(path_cp_gctx)
      exp_cp<-parse_gctx(paste0(cell_list[i],"_cp_test.gctx"))
      exp_cp<-exp_cp@mat
      
      r_matrix<-NULL
      for (j in 1:dim(exp_sh)[2]){
        r_each<-t(cor(exp_sh[,j],exp_cp,method="spearman"))
        colnames(r_each)<-colnames(exp_sh)[j]
        r_matrix<-cbind(r_matrix,r_each)
      }
      
      setwd(path_output)
      saveRDS(r_matrix, file = paste0(cell_list[i],"_merged.Rds"))
    }
  }

#####################################################################################################
#Step 2:r_matrix after filtering out the best drug dose and time point; In this strategy, we keep the best drug dose and timepoint for each sh/oe/xpr protocal.
DR_filter_drug<-function(path_input,path_output,sig_info,dir,int_cell){
  #input:
  #sig_info: loaded from "../meta_data/siginfo_beta_yuan.Rdata"
  #dir:"pos" or "neg", 
  #int_cell: one cell line name, e.g. "A549"
  
  #output :
  #r_matrix_filter: generate the r_matrix after filtering out the best drug dose and time point
  #sig_id_loc_filter: location matrix(numeric), record the location of the sig_id of the selected best dose and time point, the location is generated by comparing with the sig_info from "../meta_data/siginfo_beta_yuan.Rdata"

  setwd(path_input)#the path with the merged r_matrix data
  r_matrix<-readRDS(file=paste0(int_cell,"_merged.Rds"))#row is drug, column is sh, oe or xpr
  
  index_cp<-match(rownames(r_matrix),sig_info[,"sig_id"])
  sig_info_cp<-as.matrix(sig_info[index_cp,])# mapped to r_matrix
  uni_cp_id<-as.matrix(unique(sig_info_cp[,"pert_id"]))
  
  r_matrix_filter<-matrix(NA,length(uni_cp_id),dim(r_matrix)[2])
  sig_id_loc_filter<-matrix(NA,length(uni_cp_id),dim(r_matrix)[2])
  #r_matrix(row) and sig_info_cp are matched
  for (n in 1:length(uni_cp_id)){
    
    ind<-which(sig_info_cp[,"pert_id"]==uni_cp_id[n])
    
    if (length(ind)>1){
      int_r_matrix<-as.matrix(r_matrix[ind,])
      #int_sig_info_cp<-sig_info_cp[ind,]
      #int_r_matrix and int_sig_info_cp are matched
      if(dir=="pos"){
        r_matrix_filter[n,]=colMaxs(int_r_matrix,na.rm = T)
        loc_sig<-apply(int_r_matrix,2,which.max)#which.max will not consider NA
      }else{
        r_matrix_filter[n,]=colMins(int_r_matrix,na.rm = T)
        loc_sig<-apply(int_r_matrix,2,which.min)
      }
      
      sig_id_cp_filter=rownames(int_r_matrix)[loc_sig]
      sig_id_loc_filter[n,]=match(sig_id_cp_filter,sig_info[,"sig_id"])
      
    }
    
    if(length(ind)==1){
      r_matrix_filter[n,]=t(as.matrix(r_matrix[ind,]))
      sig_id_cp_filter=sig_info_cp[ind,"sig_id"] 
      sig_id_loc_filter[n,]=match(sig_id_cp_filter,sig_info[,"sig_id"])
    }
    
    gc()
    gc()
  }
  
  rownames(r_matrix_filter)<-uni_cp_id#row is drug pert_id
  colnames(r_matrix_filter)<-colnames(r_matrix)#colnames is one of "sh","oe","xpr"
  
  rownames(sig_id_loc_filter)<-uni_cp_id
  colnames(sig_id_loc_filter)<-colnames(r_matrix)
  
  setwd(path_output)
  saveRDS(r_matrix_filter,file=paste0(int_cell,"_Rmatrix_FilterCP.Rds"))#rownames is the best drug pert_id, colnmaes is the unfiltered sig_id of sh/oe/xpr; each element is correlation coefficient
  saveRDS(sig_id_loc_filter,file=paste0(int_cell,"_SigIDCP_FilterCP.Rds"))#rownames is the best drug pert_id, colname is the unfiltered sig_id of sh/oe/xpr; each element is the location (numeric) of  best cp sig_id by comparing the full sig_info 
  
}

#####################################################################################################
#Step3: generate r_matrix after filtering out the best sh,oe or xpr; In this strategy, we keep the shRNA, overexpression plasmid or CRISPR perturbagens with highest median correlation coefficient across all drugs
DR_filter_other_trt<-function(path_input,path_output,sig_info,dir,int_cell){
  #input:
  #path_input: the path with r_matrix (after filtering out best drug)
  #sig_info: loaded from "../meta_data/siginfo_beta_yuan.Rdata"
  #int_cell: one cell line name, e.g. "A549" 
  
  #output
  #r_matrix_filter: r_matrix after filtering out the best sh, oe or xpr; 
  #sig_id_loc_filter: location matrix (numeric),recode the location of the sig_id of the selected best dose and time point and best sh/oe/xpr;the location is generated by comparing with the sig_info from "../meta_data/siginfo_beta_yuan.Rdata"
  
  setwd(path_input)
  r_matrix<-readRDS(file=paste0(int_cell,"_Rmatrix_FilterCP.Rds"))#row is drug, column is sh, oe or xpr
  sig_id_loc<-readRDS(file=paste0(int_cell,"_SigIDCP_FilterCP.Rds"))#location of selected cp sig_id
  
  median_value<-as.matrix(colMedians(r_matrix,na.rm = T))
  rownames(median_value)<-colnames(r_matrix)
  
  log_trt<-match(colnames(r_matrix),sig_info[,"sig_id"])
  sig_info_trt<-as.matrix(sig_info[log_trt,])#r_matrix(column), median_value and sig_info_trt are matched
  uni_cmapname<-as.matrix(unique(sig_info_trt[,"cmap_name"]))
  
  check_point<-which(uni_cmapname=="")#We found the some 'cmap_name' are empty in the sig_info with pert_type=='trt_xpr'
  if(length(check_point)!=0){
    uni_cmapname<-as.matrix(uni_cmapname[-check_point,1])
  }
  
  r_matrix_filter<-matrix(NA,dim(r_matrix)[1],length(uni_cmapname))
  sig_id_trt_filter<-matrix(NA,length(uni_cmapname),1)
  for (n in 1:length(uni_cmapname)){
    
    ind<-which(sig_info_trt[,"cmap_name"]==uni_cmapname[n])
    
    if (length(ind)>1){
      int_r_matrix<-as.matrix(r_matrix[,ind])
      int_median_value<-as.matrix(median_value[ind])
      if(dir=="pos"){
        loc_sig=which.max(int_median_value)
      }else{
        loc_sig=which.min(int_median_value) 
      }
      r_matrix_filter[,n]=as.matrix(int_r_matrix[,loc_sig])
      sig_id_trt_filter[n,1]=colnames(int_r_matrix)[loc_sig]
    }
    
    if(length(ind)==1){
      r_matrix_filter[,n]=as.matrix(r_matrix[,ind])
      sig_id_trt_filter[n,1]=colnames(r_matrix)[ind]
    }
    gc()
    gc()
  }
  
  rownames(r_matrix_filter)=rownames(r_matrix)
  colnames(r_matrix_filter)<-uni_cmapname
  
  sig_id_loc_filter<-sig_id_loc[,sig_id_trt_filter]
  
  setwd(path_output)
  saveRDS(r_matrix_filter,file=paste0(int_cell,"_Rmatrix_FilterBoth.Rds"))#rowname is the best drug pert_id, colname is the cmap_name of the best sh, oe or xpr, each element is correaltion coefficient
  saveRDS(sig_id_loc_filter,file=paste0(int_cell,"_SigIDBoth_FilterBoth.Rds"))#rowname is the best drug pert_id, colname is the sig_id of the best sh, oe or xpr, each element is the location of the best drug sig_id comparing with the full sig_info
  
}
